### Trae todos los usuarios
GET http://localhost:3001/allUsers


### Inserta un nuevo usuario en la BD

POST http://localhost:3001/newUser
Content-Type: application/json

{
  "name": "eladio",
  "mail": "eladio@prueba.com",
  "password": "Hola123."  
}

### Elimina un usuario de la base
DELETE http://localhost:3001/removeUser/pepe


### Prueba de login
POST http://localhost:3001/login
Content-Type: application/json

{
  "mail": "pepe@prueba.com",
  "password": "Hola123."  
}

### Trae todos los productos
GET http://localhost:3001/allProducts