### Trae todos los usuarios
GET http://localhost:3001/users/all


### Inserta un nuevo usuario en la BD

POST http://localhost:3001/users/create
Content-Type: application/json

{
  "name": "laura",
  "mail": "LAUra@prueba.com",
  "password": "Hola123."  
}

### Elimina un usuario de la base
DELETE http://localhost:3001/users/delete


### Prueba de login
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "mail": "lauRA@prueba.com",
  "password": "Hola123."  
}

### Trae todos los productos
GET http://localhost:3001/allProducts


### Inserta un nuevo producto en la BD

POST http://localhost:3001/newProduct
Content-Type: application/json

{
  "name": "zapatos",
  "description": "zapatillas blancas deportivas air force one",
  "image": "https://imagenes.elpais.com/resizer/6MWrX16d-D4Fe7cUEDABqTyxRhs=/1200x0/cloudfront-eu-central-1.images.arcpublishing.com/prisa/D2ONULSKOJFBDJCDEI3F6L7SNM.png",
  "price": 500  
}

### Cambio de datos en el perfil

PUT http://localhost:3001/changeProfile
Content-Type: application/json

{
  "name": "laurita",
  "password": "Hola123."  
}


### Desloguearse con usuario

GET http://localhost:3001/users/logout
